/* eslint-disable @next/next/no-img-element */
import { useSession } from "next-auth/client";
import Layout from "../../components/layout";
import Head from "next/head";
import styles from "../../styles/pages/user/Favorites.module.css";
import { getSpotifyClient } from "../../sevices/spotify";
import { useState, useEffect } from "react";
import { api } from "../../sevices/api";

const Favorites = () => {
  const [session, loading] = useSession();

  if (!session)
    return (
      <Layout>
        <div className={styles.noSession}>
          <h1>No Session!</h1>
        </div>
      </Layout>
    );
  if (loading) return <div>loading...</div>;
  if (!loading && session)
    return (
      <Layout>
        <Head>
          <title>Spotifier</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {session && (
          <div className={styles.container}>
            <p>fav</p>
          </div>
        )}
      </Layout>
    );
};

export default Favorites;
