/* eslint-disable @next/next/no-img-element */
import { useSession } from "next-auth/client";
import Layout from "../../components/layout";
import Head from "next/head";
import styles from "../../styles/pages/user/Profile.module.css";
import { getSpotifyClient } from "../../sevices/spotify";
import { useState, useEffect } from "react";
import { api } from "../../sevices/api";

const Profile = () => {
  const [session, loading] = useSession();

  const [user, setUser] = useState<UserProps>();
  useEffect(() => {
    async function loadUser() {
      try {
        const spotify = await getSpotifyClient();
        const response = await spotify.get("me");

        console.log(response.data);
        setUser(response.data);
      } catch (error) {
        console.log(error);
      }
    }
    loadUser();
  }, []);

  const [topArtists, setTopArtists] = useState<Array<ArtistProps>>();
  useEffect(() => {
    async function loadTopArtists() {
      try {
        const spotify = await getSpotifyClient();
        const response = await spotify.get(
          "me/top/artists?time_range=short_term&limit=10"
        );

        console.log(response.data.items);
        setTopArtists(response.data.items);
      } catch (error) {
        console.log(error);
      }
    }
    loadTopArtists();
  }, []);

  const [topTracks, setTopTracks] = useState<Array<TrackProps>>();
  useEffect(() => {
    async function loadTopTracks() {
      try {
        const spotify = await getSpotifyClient();
        const response = await spotify.get(
          "me/top/tracks?time_range=short_term&limit=10"
        );

        console.log(response.data.items);
        setTopTracks(response.data.items);
      } catch (error) {
        console.log(error);
      }
    }
    loadTopTracks();
  }, []);

  if (loading) return <div>loading...</div>;
  if (!session)
    return (
      <Layout>
        <div className={styles.noSession}>
          <h1>No Session!</h1>
        </div>
      </Layout>
    );
  if (!loading && session)
    return (
      <Layout>
        <Head>
          <title>Spotifier</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {session && (
          <>
            <div className={styles.pageContainer}>
              <div className={styles.welcome}>
                <p className={styles.welcomeText}>
                  Welcome, <strong>{user?.display_name}</strong>!
                </p>
              </div>
              <div className={styles.contentContainer}>
                <div className={styles.artistsContainer}>
                  <p>Top 10 Artists</p>
                  {topArtists?.map((a) => (
                    <div className={styles.artist} key={a.id}>
                      <img
                        className={styles.img}
                        src={a.images[0].url}
                        alt="Picture of the artist"
                      />
                      <p className={styles.name}>{a.name}</p>
                    </div>
                  ))}
                </div>
                <div className={styles.tracksContainer}>
                  <p>Top 10 Tracks</p>
                  {topTracks?.map((a) => (
                    <div className={styles.track} key={a.id}>
                      <img
                        className={styles.img}
                        src={a.album.images[0].url}
                        alt="Picture of the album"
                      />
                      <p className={styles.name}>{a.name}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </>
        )}
      </Layout>
    );
};

export default Profile;
