import { useSession } from 'next-auth/client';
import Layout from '../../components/layout';
import Head from 'next/head'
import styles from '../../styles/pages/Profile.module.css'
import { useForm } from "react-hook-form";
import { getSpotifyClient } from '../../sevices/spotify';
import Router from "next/router";


const Profile = () => {
  const { register, handleSubmit } = useForm();
  const [session, loading] = useSession();

  if (loading) return <div>loading...</div>;
  if (!session) return (Router.push('/'));


  

  return (
    <Layout>
      <Head>
        <title>Spotifier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session && (
        <>
          
        </>
      )}
    </Layout>
  );
};

export default Profile;
